name: CI

on: [ pull_request ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: corretto
      - run: ./mvnw verify

  validate-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ./infrastructure/.nvmrc
      - name: Install infrastructure dependencies
        run: npm ci
      - name: Validate infrastructure code
        run: npm run validate
